In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [2]:
data_sh = pd.read_csv("C:/Users/e_bab/Documents/4geeks/python-hello/ml-webapp-using-flask-tutorial/Youtube05-Shakira.csv")
data_m= pd.read_csv("C:/Users/e_bab/Documents/4geeks/python-hello/ml-webapp-using-flask-tutorial/Youtube04-Eminem.csv")
data_lm=pd.read_csv("C:/Users/e_bab/Documents/4geeks/python-hello/ml-webapp-using-flask-tutorial/Youtube03-LMFAO.csv")
data_kp=pd.read_csv("C:/Users/e_bab/Documents/4geeks/python-hello/ml-webapp-using-flask-tutorial/Youtube02-KatyPerry.csv")
data_ps=pd.read_csv("C:/Users/e_bab/Documents/4geeks/python-hello/ml-webapp-using-flask-tutorial/Youtube01-Psy..csv")
print(data_sh.head(2))
print(data_sh.shape)
print(data_m.head(2))
print(data_m.shape)
print(data_lm.head(2))
print(data_lm.shape)
print(data_kp.head(2))
print(data_kp.shape)
print(data_ps.head(2))
print(data_ps.shape)

                            COMMENT_ID         AUTHOR  \
0  z13lgffb5w3ddx1ul22qy1wxspy5cpkz504     dharma pal   
1    z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj  Tiza Arellano   

                         DATE        CONTENT  CLASS  
0  2015-05-29T02:30:18.971000     Nice song      0  
1  2015-05-29T00:14:48.748000  I love song       0  
(370, 5)
                            COMMENT_ID        AUTHOR  \
0    z12rwfnyyrbsefonb232i5ehdxzkjzjs2   Lisa Wellas   
1  z130wpnwwnyuetxcn23xf5k5ynmkdpjrj04  jason graham   

                         DATE  \
0                         NaN   
1  2015-05-29T02:26:10.652000   

                                           CONTENT  CLASS  
0        +447935454150 lovely girl talk to me xxx      1  
1  I always end up coming back to this song<br />      0  
(448, 5)
                              COMMENT_ID        AUTHOR  \
0  z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k  Corey Wilson   
1  z124jvczaz3dxhnbc04cffk43oiugj25yzo0k   Epic Gaming   

                        

In [3]:
data_tot= pd.concat([data_sh,data_m, data_lm,data_kp,data_ps], axis =0, ignore_index=True)
print(data_tot.head(3))
print(data_tot.shape)

                              COMMENT_ID                              AUTHOR  \
0    z13lgffb5w3ddx1ul22qy1wxspy5cpkz504                          dharma pal   
1      z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj                       Tiza Arellano   
2  z12quxxp2vutflkxv04cihggzt2azl34pms0k  Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™    

                         DATE        CONTENT  CLASS  
0  2015-05-29T02:30:18.971000     Nice song      0  
1  2015-05-29T00:14:48.748000  I love song       0  
2  2015-05-28T21:00:08.607000  I love song       0  
(1956, 5)


In [4]:
print(data_tot.info())
print(data_tot.isnull().sum())
print(data_tot.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1956 entries, 0 to 1955
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COMMENT_ID  1956 non-null   str  
 1   AUTHOR      1956 non-null   str  
 2   DATE        1711 non-null   str  
 3   CONTENT     1956 non-null   str  
 4   CLASS       1956 non-null   int64
dtypes: int64(1), str(4)
memory usage: 397.8 KB
None
COMMENT_ID      0
AUTHOR          0
DATE          245
CONTENT         0
CLASS           0
dtype: int64
3


In [5]:
print(data_tot["CONTENT"].duplicated().sum())
content_duplicate= data_tot[data_tot["CONTENT"].duplicated(keep=False)]
print(content_duplicate[["CONTENT", "CLASS"]].sort_values("CONTENT"))

196
                                               CONTENT  CLASS
480                         Check out my SEXY VIDEO :*      1
481                         Check out my SEXY VIDEO :*      1
177                               subscribe to my feed      1
477                               subscribe to my feed      1
324  ******* Facebook is LAME and so 2004! Check ou...      1
..                                                 ...    ...
116                                         waka waka      0
120                                                wow      0
236                                                wow      0
348                                                wow      0
367                                                wow      0

[255 rows x 2 columns]


In [6]:
print("Total rows:", len(data_tot))
print("Unique comment IDs:", data_tot["COMMENT_ID"].nunique())
print("Duplicate comment IDs:", data_tot["COMMENT_ID"].duplicated().sum())
data_tot.drop_duplicates()

Total rows: 1956
Unique comment IDs: 1953
Duplicate comment IDs: 3


,COMMENT_ID,AUTHOR,DATE,CONTENT,CLASS
0,z13lgffb5w3ddx1ul22qy1wxspy5cpkz504,dharma pal,2015-05-29T02:30:18.971000,Nice song,0
1,z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj,Tiza Arellano,2015-05-29T00:14:48.748000,I love song ,0
2,z12quxxp2vutflkxv04cihggzt2azl34pms0k,Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™ ,2015-05-28T21:00:08.607000,I love song ,0
3,z12icv3ysqvlwth2c23eddlykyqut5z1h,Eric Gonzalez,2015-05-28T20:47:12.193000,"860,000,000 lets make it first female to reach...",0
4,z133stly3kete3tly22petvwdpmghrlli,Analena López,2015-05-28T17:08:29.827000,shakira is best for worldcup,0
...,...,...,...,...,...
1951,z13th1q4yzihf1bll23qxzpjeujterydj,Carmen Racasanu,2014-11-14T13:27:52,How can this have 2 billion views when there's...,0
1952,z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k,diego mogrovejo,2014-11-14T13:28:08,I don't now why I'm watching this in 2014,0
1953,z130zd5b3titudkoe04ccbeohojxuzppvbg,BlueYetiPlayz -Call Of Duty and More,2015-05-23T13:04:32,subscribe to me for call of duty vids and give...,1
1954,z12he50arvrkivl5u04cctawgxzkjfsjcc4,Photo Editor,2015-06-05T14:14:48,hi guys please my android photo editor downloa...,1


In [7]:
data_tot["CONTENT"]=data_tot["CONTENT"].str.strip()
data_tot["CONTENT"]=data_tot["CONTENT"].str.lower()
print(data_tot["CONTENT"].str.contains(r"[?,_\-,!]").sum())

876


In [8]:
from sklearn.model_selection import train_test_split

x = data_tot["CONTENT"]
y= data_tot["CLASS"]

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.head(2))

836                  thumbs up if you watched it in 2011
1688    just coming to check if people are still viewi...
Name: CONTENT, dtype: str


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

x_train_DF= vectorizer.fit_transform(x_train)
x_test_DF= vectorizer.transform(x_test)
print(x_train_DF[:2])


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23 stored elements and shape (2, 3891)>
  Coords	Values
  (0, 3443)	0.35662172455606583
  (0, 3568)	0.29929065558002715
  (0, 1827)	0.2649954804935879
  (0, 3850)	0.2098193671615491
  (0, 3694)	0.5094902284062022
  (0, 1924)	0.22512360450632818
  (0, 1855)	0.25709508084208255
  (0, 107)	0.5409625373336976
  (1, 1827)	0.1744904709819073
  (1, 1982)	0.18410187553014776
  (1, 904)	0.3045021317309813
  (1, 3463)	0.13304359047347045
  (1, 828)	0.12399622515647887
  (1, 2625)	0.20991742609214098
  (1, 498)	0.20777262360370358
  (1, 3248)	0.499848969680399
  (1, 3630)	0.39163230528113413
  (1, 3432)	0.10851701957775889
  (1, 3621)	0.14758510743649036
  (1, 454)	0.13097664069231965
  (1, 490)	0.39163230528113413
  (1, 3427)	0.260536993498424
  (1, 1144)	0.21779611241968347


In [10]:
from sklearn.svm import SVC
model_SVC= SVC(kernel="linear")
model_SVC.fit(x_train_DF, y_train)

y_pred=model_SVC.predict(x_test_DF)

print(y_pred)

from sklearn.metrics import classification_report
print(f"accuracy score is : {classification_report(y_test, y_pred)}")

[0 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 1 1
 0 0 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0
 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1
 1 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 1
 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0
 1 0 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1
 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0
 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 1 1
 1 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1
 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 1 1
 1 0 1 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1 0 0]
accuracy score is :               precision    recall  f1-score   support

           0       0.94      0.98      0.96       185
           1       0.98      0.95      0.96       207

    accuracy        

In [11]:
# comparing with keras dense, neural network 
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

tf_model = Sequential([Dense(128, activation = "relu"),
                       Dropout(0.3),
                       Dense(64, activation = "relu"), 
                       Dropout(0.3),
                       Dense(1, activation="sigmoid")
])


In [12]:
from tensorflow.keras.optimizers import Adam

tf_model.compile(optimizer=Adam(learning_rate = 0.001), loss="binary_crossentropy", metrics=["accuracy",tf.keras.metrics.Precision(),
    tf.keras.metrics.Recall()])

In [13]:
tf_model.fit(x_train_DF, y_train)
y_pred_prob= tf_model.predict(x_test_DF)
print(y_pred_prob)

y_pred= (y_pred_prob>0.5).astype(int).reshape(-1,)
print(classification_report(y_test, y_pred))

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7442 - loss: 0.6229 - precision: 0.6793 - recall: 0.9449
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
[[0.4325292 ]
 [0.7772861 ]
 [0.85477114]
 [0.7831872 ]
 [0.5631143 ]
 [0.68021667]
 [0.85477114]
 [0.6198844 ]
 [0.64580107]
 [0.7165216 ]
 [0.5444969 ]
 [0.37633133]
 [0.5533699 ]
 [0.42875037]
 [0.43913165]
 [0.41421556]
 [0.43570074]
 [0.46254975]
 [0.3785041 ]
 [0.3696996 ]
 [0.42160475]
 [0.33600333]
 [0.58367527]
 [0.38421535]
 [0.73654115]
 [0.3683796 ]
 [0.61967003]
 [0.85477114]
 [0.533164  ]
 [0.47013304]
 [0.452097  ]
 [0.47022733]
 [0.3237458 ]
 [0.81030095]
 [0.41351947]
 [0.62134933]
 [0.7682706 ]
 [0.60991454]
 [0.52328   ]
 [0.3417555 ]
 [0.46623963]
 [0.4131079 ]
 [0.47123373]
 [0.83289886]
 [0.3746429 ]
 [0.8062601 ]
 [0.797543  ]
 [0.43723267]
 [0.74694943]
 [0.60266864]
 [0.62247896]
 [0.7935114 ]
 [0.6960856 ]
 [0.77240723]
 [0.54131067]
 [0.35273233]
 [0.35816815]
 [0.7232567 ]
 [0.74767745]
 [0.48283672]
 [0.698079

In [24]:
from pickle import dump 
dump(vectorizer, open ("vectorize_youtubr_spam.sav", "wb"))
dump(model_SVC, open ("support_vector_youtube_spam.sav", "wb"))

In [14]:
#using LSTM 
tf_vectorizer = tf.keras.layers.TextVectorization(
    max_tokens=10000,
    output_mode="int",
    output_sequence_length=50
)

In [15]:
tf_vectorizer.adapt(x_train)
x_train_seq = tf_vectorizer(x_train)
x_test_seq = tf_vectorizer(x_test)
print(x_train_seq[:2])
print(x_train_seq.shape)

tf.Tensor(
[[ 112   36   24   10  455   14   23 4083    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0]
 [  28  392    6   11   24   55   45  130 1725    3   16    5 3925  135
   130  889    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0]], shape=(2, 50), dtype=int64)
(1564, 50)


In [16]:
print(x_train_seq.shape)
print(x_test_seq.shape)

print(x_train_seq[:5])
print(x_test_seq[:5])

(1564, 50)
(392, 50)
tf.Tensor(
[[ 112   36   24   10  455   14   23 4083    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0]
 [  28  392    6   11   24   55   45  130 1725    3   16    5 3925  135
   130  889    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0]
 [  50  856   66   45 2215    7 1156   43 2579  762   90    6 3734 2771
  4059  578   41  615    6   26    6   85   29    5  147    4 1155    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0]
 [  24   10   19 1093  777 1093  319 1035  175 1232 1230   98   11    8
   829 1044 3496 1591  165    4 2789 2311   93 1311    4 1160 3690   56
   269   21  111   10  157   94   41 2729  499 

In [17]:
vocab_size = len(tf_vectorizer.get_vocabulary())

print(vocab_size)

4121


In [18]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.layers import LSTM

LSTM_model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=64
    ),
    LSTM(64),
    Dense(1, activation="sigmoid")
])

In [19]:
LSTM_model.compile(optimizer= Adam(learning_rate =0.001), loss="binary_crossentropy",metrics=["accuracy"])

In [20]:
LSTM_model.fit(x_train_seq, y_train, epochs = 10, batch_size = 32)
y_pred_prob= LSTM_model.predict(x_test_seq)
print(y_pred_prob)

# 

Epoch 1/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.5512 - loss: 0.6818
Epoch 2/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7212 - loss: 0.5473
Epoch 3/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8651 - loss: 0.3987
Epoch 4/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8792 - loss: 0.3455
Epoch 5/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8804 - loss: 0.3502
Epoch 6/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8536 - loss: 0.3850
Epoch 7/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8747 - loss: 0.3807
Epoch 8/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8740 - loss: 0.3777
Epoch 9/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8779 - loss: 0.3708
Epoch 10/10
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8830 - loss: 0.3523
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[0.18527955]
 [0.18526608]
 [0.9219776 ]
 [0.18529083]
 [0.1852873 ]
 [0.18528374]
 [0.9219776 ]
 [0.1852794

In [21]:
y_pred= (y_pred_prob>0.5).astype(int).reshape(-1,)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.95      0.86       185
           1       0.94      0.77      0.85       207

    accuracy                           0.85       392
   macro avg       0.86      0.86      0.85       392
weighted avg       0.87      0.85      0.85       392

